services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oracle
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 20s
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always


  app:
    build: .
    container_name: oracle-app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: oracle
    restart: always

volumes:
  mysql-data: